# Install all python modules with pip3

---

- name: Installing all python packages with pip3
  gather_facts: false
  hosts: localhost
  user: nvidia
  tasks:
   - name: Installing numpy
     pip:
      name:
        - numpy
      extra_args: --user

   - name: Installing PyWavelets
     pip:
      name: PyWavelets

   - name: Installing ipdb
     pip:
      name: ipdb

  #  - name: Installing OpenCV Python
  #    pip:
  #     name: opencv-python

   - name: Installing Tensorflow 2 GPU
     pip:
      name: tensorflow-gpu

   - name: Installing Matplotlib
     pip:
      name: matplotlib

   - name: Installing tensorflow-datasets
     pip:
      name: tensorflow-datasets

      