# Install all python modules with pip3

---

- name: Installing all python packages with pip3
  gather_facts: false
  hosts: localhost
  user: nvidia
  tasks:
   - name: Installing numpy
     pip:
      name: numpy
      extra_args: --user

   - name: Installing PyWavelets
     pip:
      name: PyWavelets
      extra_args: --user

   - name: Installing ipdb
     pip:
      name: ipdb
      extra_args: --user

  #  - name: Installing OpenCV Python
  #    pip:
  #     name: opencv-python

   - name: Installing Tensorflow 2 GPU
     pip:
      name: tensorflow-gpu
      extra_args: --user

   - name: Installing Matplotlib
     pip:
      name: matplotlib
      extra_args: --user

   - name: Installing tensorflow-datasets
     pip:
      name: tensorflow-datasets
      extra_args: --user

      